<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>


	<!-- NuGet Package Information -->
	<PackageId>MatinDeWet.Pagination</PackageId>
	<Version>1.0.0</Version>
	<Authors>MatinDeWet</Authors>
	<Description>Pagination allows you to create paged results while making use of entity framework core</Description>
	<PackageTags>pagination</PackageTags>
	<PackageIcon>icon.png</PackageIcon>

	<!-- GPL-3.0 License -->
	<PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>

	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/MatinDeWet/Pagination</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>

	<!-- Required for GPL compliance -->
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<Copyright>Copyright © $(Authors) $([System.DateTime]::Now.Year)</Copyright>
  </PropertyGroup>

	<ItemGroup>
		<None Include="../README.md" Pack="true" PackagePath="/" />
		<None Include="../icon.png" Pack="true" PackagePath="/" Condition="Exists('../icon.png')" />
		<None Include="../LICENSE.txt" Pack="true" PackagePath="/" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
  </ItemGroup>

</Project>
